/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import Modelo.Conexion;
import TiendaMusica.Disco;
import TiendaMusica.Poster;

/**
 *
 * @author matia
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botonesInsertar = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtPrecioInsertar = new javax.swing.JTextField();
        lblPrecioInsertar = new javax.swing.JLabel();
        txtDimensionesInsertar = new javax.swing.JTextField();
        txtCantidadInsertar = new javax.swing.JTextField();
        txtNombreInsertar = new javax.swing.JTextField();
        lblCodigoInsertar = new javax.swing.JLabel();
        lblDimensionesInsertar = new javax.swing.JLabel();
        txtCodigoInsertar = new javax.swing.JTextField();
        lblCantidadInsertar = new javax.swing.JLabel();
        lblNombreInsertar = new javax.swing.JLabel();
        lblBandaInsertar = new javax.swing.JLabel();
        txtBandaInsertar = new javax.swing.JTextField();
        lblAnnioInsertar = new javax.swing.JLabel();
        txtAnnioInsertar = new javax.swing.JTextField();
        radPoster = new javax.swing.JRadioButton();
        radDisco = new javax.swing.JRadioButton();
        btnInsertarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Compra de Productos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Busqueda de Compras", jPanel4);

        jButton1.setText("Eliminar");

        jButton2.setText("Modificar");

        jButton3.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(97, 97, 97)
                .addComponent(jButton3)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(74, 74, 74))
        );

        jTabbedPane2.addTab("Productos", jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(586, 532));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecioInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioInsertar.setText("Inserte precio producto");
        txtPrecioInsertar.setFocusable(false);
        txtPrecioInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioInsertarFocusLost(evt);
            }
        });
        txtPrecioInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 177, 168, -1));

        lblPrecioInsertar.setText("Precio");
        jPanel2.add(lblPrecioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 173, -1, -1));

        txtDimensionesInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtDimensionesInsertar.setText("Inserte dimensiones poster");
        txtDimensionesInsertar.setFocusable(false);
        txtDimensionesInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDimensionesInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDimensionesInsertarFocusLost(evt);
            }
        });
        txtDimensionesInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDimensionesInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtDimensionesInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 251, 168, -1));

        txtCantidadInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadInsertar.setText("Inserte cantidad producto");
        txtCantidadInsertar.setFocusable(false);
        txtCantidadInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantidadInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 214, 168, -1));

        txtNombreInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreInsertar.setText("Inserte nombre producto");
        txtNombreInsertar.setFocusable(false);
        txtNombreInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreInsertarFocusLost(evt);
            }
        });
        txtNombreInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 140, 168, -1));

        lblCodigoInsertar.setText("Codigo");
        jPanel2.add(lblCodigoInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 103, -1, -1));

        lblDimensionesInsertar.setText("Dimensiones");
        jPanel2.add(lblDimensionesInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 247, -1, -1));

        txtCodigoInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoInsertar.setText("Inserte codigo producto");
        txtCodigoInsertar.setToolTipText("");
        txtCodigoInsertar.setFocusable(false);
        txtCodigoInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoInsertarFocusLost(evt);
            }
        });
        txtCodigoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigoInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 103, 168, -1));

        lblCantidadInsertar.setText("Cantidad");
        jPanel2.add(lblCantidadInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 214, -1, -1));

        lblNombreInsertar.setText("Nombre");
        jPanel2.add(lblNombreInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 140, -1, -1));

        lblBandaInsertar.setText("Banda");
        jPanel2.add(lblBandaInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 288, -1, -1));

        txtBandaInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtBandaInsertar.setText("Inserte banda del disco");
        txtBandaInsertar.setFocusable(false);
        txtBandaInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBandaInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBandaInsertarFocusLost(evt);
            }
        });
        txtBandaInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBandaInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtBandaInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 288, 168, -1));

        lblAnnioInsertar.setText("Año");
        jPanel2.add(lblAnnioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 321, -1, -1));

        txtAnnioInsertar.setForeground(new java.awt.Color(102, 102, 102));
        txtAnnioInsertar.setText("Inserte año del disco");
        txtAnnioInsertar.setFocusable(false);
        txtAnnioInsertar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnnioInsertarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnnioInsertarFocusLost(evt);
            }
        });
        txtAnnioInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnioInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnnioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 325, 168, -1));

        grupo_botonesInsertar.add(radPoster);
        radPoster.setText("Poster");
        radPoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPosterActionPerformed(evt);
            }
        });
        jPanel2.add(radPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 62, -1, -1));

        grupo_botonesInsertar.add(radDisco);
        radDisco.setText("Disco");
        radDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDiscoActionPerformed(evt);
            }
        });
        jPanel2.add(radDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 62, -1, -1));

        btnInsertarProducto.setText("Insertar Producto");
        btnInsertarProducto.setEnabled(false);
        btnInsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsertarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 362, 154, 41));

        jTabbedPane2.addTab("Insertar Productos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoInsertarActionPerformed

    private void txtNombreInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreInsertarActionPerformed

    private void txtCantidadInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadInsertarActionPerformed

    private void txtDimensionesInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDimensionesInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDimensionesInsertarActionPerformed

    private void txtPrecioInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioInsertarActionPerformed

    private void txtBandaInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBandaInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBandaInsertarActionPerformed

    private void txtAnnioInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnioInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnioInsertarActionPerformed

    private void radPosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPosterActionPerformed
        // TODO add your handling code here:
        txtCodigoInsertar.setFocusable(true);
        txtCodigoInsertar.setForeground(Color.black);
        txtNombreInsertar.setFocusable(true);
        txtNombreInsertar.setForeground(Color.black);
        txtPrecioInsertar.setFocusable(true);
        txtPrecioInsertar.setForeground(Color.black);
        txtDimensionesInsertar.setFocusable(true);
        txtDimensionesInsertar.setForeground(Color.black);
        txtBandaInsertar.setFocusable(false);
        txtBandaInsertar.setForeground(Color.gray);
        txtAnnioInsertar.setFocusable(false);
        txtAnnioInsertar.setForeground(Color.gray);
        btnInsertarProducto.setEnabled(true);
    }//GEN-LAST:event_radPosterActionPerformed

    private void radDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDiscoActionPerformed
        // TODO add your handling code here:
        txtCodigoInsertar.setFocusable(true);
        txtCodigoInsertar.setForeground(Color.black);
        txtNombreInsertar.setFocusable(true);
        txtNombreInsertar.setForeground(Color.black);
        txtPrecioInsertar.setFocusable(true);
        txtPrecioInsertar.setForeground(Color.black);
        txtDimensionesInsertar.setFocusable(false);
        txtDimensionesInsertar.setForeground(Color.gray);
        txtBandaInsertar.setFocusable(true);
        txtBandaInsertar.setForeground(Color.black);
        txtAnnioInsertar.setFocusable(true);
        txtAnnioInsertar.setForeground(Color.black);
        btnInsertarProducto.setEnabled(true);
    }//GEN-LAST:event_radDiscoActionPerformed

    //----------BOTON PARA INSERTAR PRODUCTOS A LA BASE DE DATOS----------------- ***AUN NO HA SIDO TESTEADO***
    private void btnInsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarProductoActionPerformed
        Poster poster = new Poster();
        Disco disco = new Disco();
        Conexion con = new Conexion();
        
        //El if
        if(radPoster.isSelected())
        {
            poster.setCodigo(txtCodigoInsertar.getText());
            poster.setNombre(txtNombreInsertar.getText());
            poster.setPrecio(Integer.parseInt(txtPrecioInsertar.getText()));
            poster.setDimension(txtDimensionesInsertar.getText());
            con.insertarPoster(poster);
        }
        else
        {
            disco.setCodigo(txtCodigoInsertar.getText());
            disco.setNombre(txtNombreInsertar.getText());
            disco.setPrecio(Integer.parseInt(txtPrecioInsertar.getText()));
            disco.setBanda(txtBandaInsertar.getText());
            disco.setAnnio(Integer.parseInt(txtAnnioInsertar.getText()));
            con.insertarDisco(disco);
        }
    }//GEN-LAST:event_btnInsertarProductoActionPerformed


                    //FocusGained Y FocusLost para la pestaña "Insertar Producto" para poner el texto por defecto si no se ha alterado
    private void txtCodigoInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoInsertarFocusGained
        if(txtCodigoInsertar.getText().equals("Inserte codigo producto")){
        txtCodigoInsertar.setText("");
        }
    }//GEN-LAST:event_txtCodigoInsertarFocusGained

    private void txtCodigoInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoInsertarFocusLost
        if(txtCodigoInsertar.getText().equals("")){
            txtCodigoInsertar.setText("Inserte codigo producto");
        }
    }//GEN-LAST:event_txtCodigoInsertarFocusLost

    private void txtNombreInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreInsertarFocusGained
        if(txtNombreInsertar.getText().equals("Inserte nombre producto")){
        txtNombreInsertar.setText("");
        }
    }//GEN-LAST:event_txtNombreInsertarFocusGained

    private void txtNombreInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreInsertarFocusLost
        if(txtNombreInsertar.getText().equals("")){
            txtNombreInsertar.setText("Inserte nombre producto");
        }
    }//GEN-LAST:event_txtNombreInsertarFocusLost

    private void txtPrecioInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioInsertarFocusGained
        if(txtPrecioInsertar.getText().equals("Inserte precio producto")){
            txtPrecioInsertar.setText("");
        }
    }//GEN-LAST:event_txtPrecioInsertarFocusGained

    private void txtPrecioInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioInsertarFocusLost
        if(txtPrecioInsertar.getText().equals("")){
            txtPrecioInsertar.setText("Inserte precio producto");
        }
    }//GEN-LAST:event_txtPrecioInsertarFocusLost

    private void txtDimensionesInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDimensionesInsertarFocusGained
        if(txtDimensionesInsertar.getText().equals("Inserte dimensiones poster")){
            txtDimensionesInsertar.setText("");
        }
    }//GEN-LAST:event_txtDimensionesInsertarFocusGained

    private void txtDimensionesInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDimensionesInsertarFocusLost
        if(txtDimensionesInsertar.getText().equals("")){
            txtDimensionesInsertar.setText("Inserte dimensiones poster");
        }
    }//GEN-LAST:event_txtDimensionesInsertarFocusLost

    private void txtBandaInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBandaInsertarFocusGained
        if(txtBandaInsertar.getText().equals("Inserte banda del disco")){
            txtBandaInsertar.setText("");
        }
    }//GEN-LAST:event_txtBandaInsertarFocusGained

    private void txtBandaInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBandaInsertarFocusLost
        if(txtBandaInsertar.getText().equals("")){
            txtBandaInsertar.setText("Inserte banda del disco");
        }
    }//GEN-LAST:event_txtBandaInsertarFocusLost

    private void txtAnnioInsertarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnnioInsertarFocusGained
        if(txtAnnioInsertar.getText().equals("Inserte año del disco")){
            txtAnnioInsertar.setText("");
        }
    }//GEN-LAST:event_txtAnnioInsertarFocusGained

    private void txtAnnioInsertarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnnioInsertarFocusLost
        if(txtAnnioInsertar.getText().equals("")){
            txtAnnioInsertar.setText("Inserte año del disco");
        }
    }//GEN-LAST:event_txtAnnioInsertarFocusLost
                //fin de los FOCUS GAINED y FOCUS LOST de la pestaña "Insertar Productos"
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertarProducto;
    private javax.swing.ButtonGroup grupo_botonesInsertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAnnioInsertar;
    private javax.swing.JLabel lblBandaInsertar;
    private javax.swing.JLabel lblCantidadInsertar;
    private javax.swing.JLabel lblCodigoInsertar;
    private javax.swing.JLabel lblDimensionesInsertar;
    private javax.swing.JLabel lblNombreInsertar;
    private javax.swing.JLabel lblPrecioInsertar;
    private javax.swing.JRadioButton radDisco;
    private javax.swing.JRadioButton radPoster;
    private javax.swing.JTextField txtAnnioInsertar;
    private javax.swing.JTextField txtBandaInsertar;
    private javax.swing.JTextField txtCantidadInsertar;
    private javax.swing.JTextField txtCodigoInsertar;
    private javax.swing.JTextField txtDimensionesInsertar;
    private javax.swing.JTextField txtNombreInsertar;
    private javax.swing.JTextField txtPrecioInsertar;
    // End of variables declaration//GEN-END:variables
}
